In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
import tensorflow_hub as hub

print(f"TensorFlow Version: {tf.__version__}")
print(f"Keras Version: {tf.keras.__version__}")

TensorFlow Version: 2.21.0
Keras Version: 3.14.1


In [3]:
tfds.list_builders() # check for the avilable datasets inside tensor_flow

['abstract_reasoning',
 'accentdb',
 'aeslc',
 'aflw2k3d',
 'ag_news_subset',
 'ai2_arc',
 'ai2_arc_with_ir',
 'ai2dcaption',
 'aloha_mobile',
 'amazon_us_reviews',
 'anli',
 'answer_equivalence',
 'arc',
 'asimov_dilemmas_auto_val',
 'asimov_dilemmas_scifi_train',
 'asimov_dilemmas_scifi_val',
 'asimov_injury_val',
 'asimov_multimodal_auto_val',
 'asimov_multimodal_manual_val',
 'asimov_v2_constraints_with_rationale',
 'asimov_v2_constraints_without_rationale',
 'asimov_v2_injuries',
 'asimov_v2_videos',
 'asqa',
 'asset',
 'assin2',
 'asu_table_top_converted_externally_to_rlds',
 'austin_buds_dataset_converted_externally_to_rlds',
 'austin_sailor_dataset_converted_externally_to_rlds',
 'austin_sirius_dataset_converted_externally_to_rlds',
 'bair_robot_pushing_small',
 'bc_z',
 'bccd',
 'beans',
 'bee_dataset',
 'beir',
 'berkeley_autolab_ur5',
 'berkeley_cable_routing',
 'berkeley_fanuc_manipulation',
 'berkeley_gnm_cory_hall',
 'berkeley_gnm_recon',
 'berkeley_gnm_sac_son',
 'berkel

In [4]:
(train_data, validation_data, test_data), metadata = tfds.load(
'imdb_reviews',
split=['train[0%:80%]', 'train[80%:90%]', 'train[90%:100%]'],
with_info=True,
as_supervised=True,)  # create 03 datasets, for training, testing and validation

In [5]:
train_data

<_PrefetchDataset element_spec=(TensorSpec(shape=(), dtype=tf.string, name=None), TensorSpec(shape=(), dtype=tf.int64, name=None))>

In [6]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(2))) #read user-reviews
train_examples_batch

I0000 00:00:1780342237.332213 11101157 tf_record_dataset_op.cc:396] The default buffer size is 262144, which is overridden by the user specified `buffer_size` of 8388608
W0000 00:00:1780342237.333585 11100990 cache_dataset_ops.cc:912] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset  will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.


<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

In [7]:
train_labels_batch

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 0])>

In [8]:
pretrained_model = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"

# Custom Keras 3 Compatibility Wrapper for Legacy TF-Hub Layers
class HubEmbeddingLayer(tf.keras.layers.Layer):
    def __init__(self, handle, trainable=True, **kwargs):
        super().__init__(**kwargs)
        self.handle = handle
        self.trainable = trainable
        self.hub_layer = hub.KerasLayer(handle, trainable=trainable)
        
    def call(self, inputs):
        # Flatten inputs to a 1D string tensor as expected by the Swivel model
        flat_inputs = tf.reshape(inputs, [-1])
        return self.hub_layer(flat_inputs)
        
    def compute_output_shape(self, input_shape):
        return (input_shape[0], 20)

# Create modern TF-Hub layer
hub_layer = HubEmbeddingLayer(pretrained_model, trainable=True)

In [9]:
hub_layer(train_examples_batch[:2]) # encoded view of the frist two review feedbacks

<tf.Tensor: shape=(2, 20), dtype=float32, numpy=
array([[ 1.765786  , -3.882232  ,  3.9134233 , -1.5557289 , -3.3362343 ,
        -1.7357955 , -1.9954445 ,  1.2989551 ,  5.081598  , -1.1041286 ,
        -2.0503852 , -0.72675157, -0.65675956,  0.24436149, -3.7208383 ,
         2.0954835 ,  2.2969332 , -2.0689783 , -2.9489717 , -1.1315987 ],
       [ 1.8804485 , -2.5852382 ,  3.4066997 ,  1.0982676 , -4.056685  ,
        -4.891284  , -2.785554  ,  1.3874227 ,  3.8476458 , -0.9256538 ,
        -1.896706  ,  1.2113281 ,  0.11474707,  0.76209456, -4.8791065 ,
         2.906149  ,  4.7087674 , -2.3652055 , -3.5015898 , -1.6390051 ]],
      dtype=float32)>

In [10]:
train_examples_batch[:2]

<tf.Tensor: shape=(2,), dtype=string, numpy=
array([b"This was an absolutely terrible movie. Don't be lured in by Christopher Walken or Michael Ironside. Both are great actors, but this must simply be their worst role in history. Even their great acting could not redeem this movie's ridiculous storyline. This movie is an early nineties US propaganda piece. The most pathetic scenes were those when the Columbian rebels were making their cases for revolutions. Maria Conchita Alonso appeared phony, and her pseudo-love affair with Walken was nothing but a pathetic emotional plug in a movie that was devoid of any real meaning. I am disappointed that there are movies like this, ruining actor's like Christopher Walken's good name. I could barely sit through it.",
       b'I have been known to fall asleep during films, but this is usually due to a combination of things including, really tired, being warm and comfortable on the sette and having just eaten a lot. However on this occasion I fell a

In [11]:
model = tf.keras.Sequential()
model.add(tf.keras.Input(shape=(), dtype=tf.string)) # Input specifier for Keras 3 symbolic tracing
model.add(hub_layer) # input layer is the encoded output from tensor_flow hub neural networ
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ hub_embedding_layer             │ (None, 20)             │             0 │
│ (HubEmbeddingLayer)             │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 16)             │           336 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 353 (1.38 KB)

 Trainable params: 353 (1.38 KB)

 Non-trainable params: 0 (0.00 B)

In [12]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])  # back_prop configuration

In [13]:
model.fit(train_data.shuffle(10000).batch(512),
         epochs=20,
         validation_data=validation_data.batch(512),
         verbose=1)

Epoch 1/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 12s 318ms/step - accuracy: 0.5059 - loss: 1.7550


 6/40 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4992 - loss: 1.6795  


12/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4987 - loss: 1.5808


18/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5002 - loss: 1.4921


24/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5024 - loss: 1.4160


30/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5039 - loss: 1.3535


36/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5050 - loss: 1.3024 


40/40 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - accuracy: 0.5088 - loss: 1.0117 - val_accuracy: 0.5072 - val_loss: 0.7935


Epoch 2/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.5039 - loss: 0.8064


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4997 - loss: 0.7901 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5037 - loss: 0.7828


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5080 - loss: 0.7772


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5108 - loss: 0.7734


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5129 - loss: 0.7709


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5149 - loss: 0.7687


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5281 - loss: 0.7544 - val_accuracy: 0.5404 - val_loss: 0.7348


Epoch 3/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5723 - loss: 0.7070


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5556 - loss: 0.7243 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5557 - loss: 0.7244


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5550 - loss: 0.7239


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5534 - loss: 0.7235


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5531 - loss: 0.7227


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5530 - loss: 0.7220


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5548 - loss: 0.7166 - val_accuracy: 0.5752 - val_loss: 0.7000


Epoch 4/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.5879 - loss: 0.6853


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5775 - loss: 0.6916 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5791 - loss: 0.6910


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5798 - loss: 0.6907


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5799 - loss: 0.6905


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5799 - loss: 0.6905


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5801 - loss: 0.6904


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5825 - loss: 0.6892 - val_accuracy: 0.5952 - val_loss: 0.6756


Epoch 5/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.5938 - loss: 0.6755


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6098 - loss: 0.6671 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6063 - loss: 0.6700


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6040 - loss: 0.6711


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6031 - loss: 0.6716


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6024 - loss: 0.6719


38/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6021 - loss: 0.6719


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6011 - loss: 0.6708 - val_accuracy: 0.6176 - val_loss: 0.6569


Epoch 6/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.6523 - loss: 0.6334


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6254 - loss: 0.6518 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6225 - loss: 0.6530


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6215 - loss: 0.6539


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6210 - loss: 0.6543


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6203 - loss: 0.6547


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6197 - loss: 0.6550


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6169 - loss: 0.6569 - val_accuracy: 0.6256 - val_loss: 0.6446


Epoch 7/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.5938 - loss: 0.6658


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6186 - loss: 0.6526 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6207 - loss: 0.6504


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6233 - loss: 0.6492


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6250 - loss: 0.6485


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6259 - loss: 0.6483


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6265 - loss: 0.6481


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6293 - loss: 0.6471 - val_accuracy: 0.6368 - val_loss: 0.6351


Epoch 8/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.6250 - loss: 0.6523


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6314 - loss: 0.6443 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6285 - loss: 0.6447


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6301 - loss: 0.6432


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6313 - loss: 0.6422


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6322 - loss: 0.6418


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6328 - loss: 0.6415


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6374 - loss: 0.6392 - val_accuracy: 0.6420 - val_loss: 0.6278


Epoch 9/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.6406 - loss: 0.6234


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6375 - loss: 0.6369 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6401 - loss: 0.6359


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6408 - loss: 0.6353


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6417 - loss: 0.6346


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6424 - loss: 0.6340


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6429 - loss: 0.6337


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6451 - loss: 0.6321 - val_accuracy: 0.6504 - val_loss: 0.6218


Epoch 10/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.6465 - loss: 0.6208


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6378 - loss: 0.6273 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6420 - loss: 0.6254


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6453 - loss: 0.6252


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6470 - loss: 0.6251


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6476 - loss: 0.6254


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6478 - loss: 0.6258


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6503 - loss: 0.6266 - val_accuracy: 0.6564 - val_loss: 0.6154


Epoch 11/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 33ms/step - accuracy: 0.6270 - loss: 0.6323


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6446 - loss: 0.6254 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6480 - loss: 0.6253


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6494 - loss: 0.6248


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6503 - loss: 0.6240


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6511 - loss: 0.6237


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6517 - loss: 0.6234


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6552 - loss: 0.6212 - val_accuracy: 0.6612 - val_loss: 0.6102


Epoch 12/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 28ms/step - accuracy: 0.6543 - loss: 0.6225


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6464 - loss: 0.6236 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6490 - loss: 0.6223


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6524 - loss: 0.6201


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6540 - loss: 0.6193


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6558 - loss: 0.6183


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6568 - loss: 0.6179


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6615 - loss: 0.6160 - val_accuracy: 0.6696 - val_loss: 0.6054


Epoch 13/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 34ms/step - accuracy: 0.6348 - loss: 0.6448


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6525 - loss: 0.6218 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6576 - loss: 0.6156


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6593 - loss: 0.6135


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6603 - loss: 0.6128


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6612 - loss: 0.6125


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6617 - loss: 0.6123


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6654 - loss: 0.6115 - val_accuracy: 0.6736 - val_loss: 0.6017


Epoch 14/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - accuracy: 0.6543 - loss: 0.5975


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6639 - loss: 0.6024 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6679 - loss: 0.6013


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6708 - loss: 0.5999


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6706 - loss: 0.6008


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6701 - loss: 0.6019


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6698 - loss: 0.6030


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6694 - loss: 0.6074 - val_accuracy: 0.6804 - val_loss: 0.5987


Epoch 15/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.6504 - loss: 0.6307


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6637 - loss: 0.6104 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6633 - loss: 0.6084


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6646 - loss: 0.6071


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6663 - loss: 0.6062


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6674 - loss: 0.6058


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6683 - loss: 0.6055


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6727 - loss: 0.6039 - val_accuracy: 0.6852 - val_loss: 0.5941


Epoch 16/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.6738 - loss: 0.5995


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6823 - loss: 0.5929 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6821 - loss: 0.5927


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6819 - loss: 0.5933


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6812 - loss: 0.5945


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6801 - loss: 0.5959


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6796 - loss: 0.5966


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6775 - loss: 0.6003 - val_accuracy: 0.6864 - val_loss: 0.5910


Epoch 17/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 32ms/step - accuracy: 0.7168 - loss: 0.5667


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6963 - loss: 0.5784 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6931 - loss: 0.5814


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6903 - loss: 0.5843


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6884 - loss: 0.5866


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6868 - loss: 0.5882


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6853 - loss: 0.5897


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6789 - loss: 0.5973 - val_accuracy: 0.6908 - val_loss: 0.5883


Epoch 18/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.6875 - loss: 0.5915


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6717 - loss: 0.6019 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6747 - loss: 0.5989


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6766 - loss: 0.5971


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6780 - loss: 0.5961


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6788 - loss: 0.5957


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6794 - loss: 0.5954


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6820 - loss: 0.5941 - val_accuracy: 0.6904 - val_loss: 0.5853


Epoch 19/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 27ms/step - accuracy: 0.6855 - loss: 0.5847


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6770 - loss: 0.5941 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6806 - loss: 0.5924


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6816 - loss: 0.5920


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6825 - loss: 0.5912


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6833 - loss: 0.5907


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6836 - loss: 0.5907


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6845 - loss: 0.5912 - val_accuracy: 0.6912 - val_loss: 0.5833


Epoch 20/20



 1/40 ━━━━━━━━━━━━━━━━━━━━ 1s 30ms/step - accuracy: 0.6934 - loss: 0.5710


 7/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6867 - loss: 0.5785 


13/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6880 - loss: 0.5792


19/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6879 - loss: 0.5806


25/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6875 - loss: 0.5818


31/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6876 - loss: 0.5827


37/40 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6873 - loss: 0.5837


40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6867 - loss: 0.5884 - val_accuracy: 0.6940 - val_loss: 0.5813


In [14]:
model.predict(tf.constant(["This is the worst movie I have ever seen",
              "An excellent movie that I enjoyed a lot",
              "how can one make such a horrible movie? there is no story, acting direction everything is very poor"]))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step


array([[0.38093248],
       [0.6340815 ],
       [0.43646735]], dtype=float32)

In [15]:
model.predict(tf.constant(["An excellent movie that I enjoyed a lot"]))



1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step


array([[0.6340815]], dtype=float32)